---

R1:
    hostname: "192.168.159.201"
    groups:
        - cisco_group

R2:
    hostname: "192.168.159.202"
    groups:
        - cisco_group

R3:
    hostname: "192.168.159.203"
    groups:
        - cisco_group
        
R4:
    hostname: "192.168.159.204"
    groups:
        - cisco_group

R5:
    hostname: "192.168.159.205"
    groups:
        - cisco_group
        
        